config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get 'home/welcome'
  get 'about', to: 'home#about'
  resources :posts do
    collection do
      get 'work', to: 'posts#work'
      get 'life', to: 'posts#life'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :publish, -> { where(publish_at < Time.now) }
  scope :work, -> { where( category: "work") }
  scope :life, -> { where( category: "life") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def work
    @posts = Post.work
    render :index
  end

  def life
    @posts = Post.life
    render :index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :category, :content, :publish_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    @page_title || ENV["BLOG_NAME"]
  end

  def meta_description
    @meta_description || "VincentJiang's Blog"
  end

  def keyword
    @keyword = "#{@post.title if @post} ruby rails RubyOnRails web develop"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/welcome.html.slim
= image_tag "http://vincentjiang.qiniudn.com/ruby.png", class: "img-responsive img-center"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = page_title
    meta charset="utf-8"
    meta name="author" content="VincentJiang"
    meta name="keyword" content=keyword
    meta name="description" content=meta_description
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    .container
      header.text-center
        h1
          = link_to "VincentJiang", root_path, class: "blog-author"
        ul.list-inline
          li
            = link_to "Home", root_path
          li
            = link_to "Work", work_posts_path
          li
            = link_to "Life", life_posts_path
          li
            = link_to "About", about_path
      main
        == yield
    == javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :publish_at
    = f.datetime_select :publish_at
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Title
      th Category
      th Content
      th Publish at
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.category
        td = post.content
        td = post.publish_at
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Category:
  = @post.category
p
  strong Content:
  = @post.content
p
  strong Publish at:
  = @post.publish_at

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path